### ISSUE TITLE
there is bug sometimes

### ISSUE THREAD

**Issue by avi326** [Luodian/Otter#104]
![image](https://user-images.githubusercontent.com/20811190/236891599-addc01f5-3b24-4317-aec8-578c8235b8e5.png)

for example.

**Comment by Luodian** [comment]
hi it's probably a session collision bug from our local server. There is one process listening user input and send to the model process. During our test, if multiple users send request, there's likely the model process will have the session collision bug. You can try click `clean generation` to see if the problem dismissed. Otherwise we need to relaunch our model.

We are also working on fixing this issue!
