### ISSUE TITLE
Confusion regarding model versions?

### ISSUE THREAD

**Issue by vishaal27** [Luodian/Otter#126]
Hi, with release of the new [MIMIC-IT paper](https://arxiv.org/abs/2306.05425)---I am bit confused regarding the different model versions you have. Is the model on [huggingface](https://huggingface.co/luodian/otter-9b-hf) the same as the ones for which you report results in the paper? As I understand it, the results in the paper come from instruction fine-tuning OpenFlamingo on the larger MIMIC-IT dataset whereas the one on huggingface is fine-tuned on an older, slightly smaller version?
If the two models are different, are the weights of the new model already provided on huggingface?
Further, you mention in your readme that there is a new OtterV2 model that you've released---Is this the newer model you describe in the paper? If yes, could you also provide the links to these model weights?
Thanks for your incredible contributions, and looking forward to playing around with the new Otter models!

**Comment by Luodian** [comment]
hi thanks for your attention!

Original HF model was old version. And we are going to provide newer version (which is v0.2 we mentioned) soon this or next week. 

The new model's architectures is little bit different since we need to make it compatible with video inputs. So please use our updated model from `otter/modeling_otter.py` to initiate `otter_model = OtterForConditionalGeneration(....)`
