### ISSUE TITLE
Is it possible to provide a system message to Otter?

### ISSUE THREAD

**Issue by LarsDoorenbos** [Luodian/Otter#240]
Hey,

Thank you for releasing the code, weights and data. I was wondering if it is possible to provide a system message to Otter, like you do to e.g. ChatGPT, specifying something that should hold for the entire conversation?

Thanks!

**Comment by Luodian** [comment]
Currently the answer is possibly not. Because we use small MPT7B/LLAMA7B as LLM. The ability of such LLMs may not support adding system message (I will use sys msg next for brevity). 

Supposedly it's because adding sys msg will increase the input context length to LLM and be challenging for it to understanding sys msg + instructions. Another problem it's because we dont add sys msg to prompt during training Otter on MIMIC-IT data.

**Comment by LarsDoorenbos** [comment]
Okay, thank you!
