### ISSUE TITLE
`gradio_web_server` is outdated

### ISSUE THREAD

**Issue by StrangeTcy** [Luodian/Otter#323]
https://github.com/Luodian/Otter/blob/8b386816ec67b15833cde3dcd1d7ca6a752d2451/pipeline/serve/gradio_web_server.py#L16 -- this no longer works since `pipeline.constants` doesn't exist.
But `LOGDIR` is defined in https://github.com/Luodian/Otter/blob/8b386816ec67b15833cde3dcd1d7ca6a752d2451/pipeline/serve/serving_utils.py#L11

ETA: `gradio_patch` starts with a comments saying `Adopted from https://github.com/gradio-app/gradio/blob/main/gradio/components.py`, and `gradio/components.py` doesn't exist. Nor does `gradio/components/components.py`

ETA: Ah, yes, `pipeline/serve/examples` doesn't exist either

**Comment by Luodian** [comment]
hi you could take a look at this branch:

https://github.com/Luodian/Otter/tree/model_serving/pipeline/serve/examples

Your suggestions on code polish is quite good and I will definitely take them to refine our code. Current issue is due to the shift from previously Otter's serving method into OtterHD's serving method.
