### ISSUE TITLE
Link to download the old Otter-HD models

### ISSUE THREAD

**Issue by codonna9** [Luodian/Otter#325]
Hi, 
Thank you very much for releasing the code, paper and the models. I'm looking forwards to the release of Otter-HD model trained on new data. 
In the mean time, I tried the old Otter-HD model demo and I found it worked quite well for my task, which is to recognize small object presence in high-resolution images. Since the training of the new Otter-HD model will probably take a long time, could you make the old Otter-HD models available for download?

**Comment by Luodian** [comment]
Hi thanks for your interests! We are still working on the training of OtterHD weights for better performance after previously we experienced a few weeks GPU shortage and have to switch everything into new develop environment. So the release is delayed. Honestly we are not into an urge release of current OtterHD weights since we still have some methods and datasets to experiment on in order to better polish our paper...Sorry for any inconvinience.

**Comment by codonna9** [comment]
Thank you for your reply. I'll wait for the new weights then.
